#!/bin/bash
#
# Xi compiler build script
#

make cowabunga

gradle assemble --no-daemon

PHYS_DIR=`pwd -P`
RESULT=$PHYS_DIR/xic

echo "Compiler built: $RESULT"

echo 'java -jar "'$PHYS_DIR'/build/libs/cowabunga-1.0.jar" "$@"' > xic
chmod +x xic
