
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package cyr7.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNDERSCORE = 26;
  public static final int R_BRACE = 22;
  public static final int LENGTH = 9;
  public static final int TYPE_BOOL = 12;
  public static final int LT = 35;
  public static final int L_PAREN = 17;
  public static final int error = 1;
  public static final int ASSIGN = 27;
  public static final int MINUS = 29;
  public static final int DIVIDE = 32;
  public static final int RETURN = 6;
  public static final int MULT = 30;
  public static final int SEMICOLON = 24;
  public static final int INT_LITERAL = 13;
  public static final int ELSE = 5;
  public static final int XI_FILE = 3;
  public static final int ID = 10;
  public static final int R_PAREN = 18;
  public static final int EOF = 0;
  public static final int IF = 4;
  public static final int L_BRACE = 21;
  public static final int L_SQ_BRKT = 19;
  public static final int COMMA = 25;
  public static final int TYPE_INT = 11;
  public static final int EQUALS = 33;
  public static final int IXI_FILE = 2;
  public static final int USE = 7;
  public static final int HIGH_MULT = 31;
  public static final int LOGICAL_AND = 41;
  public static final int NOT_EQUALS = 34;
  public static final int COLON = 23;
  public static final int LOGICAL_OR = 42;
  public static final int GT = 37;
  public static final int BOOL_LITERAL = 16;
  public static final int NEG_BOOL = 39;
  public static final int REMAINDER = 40;
  public static final int GTE = 38;
  public static final int WHILE = 8;
  public static final int STRING_LITERAL = 14;
  public static final int CHAR_LITERAL = 15;
  public static final int LTE = 36;
  public static final int R_SQ_BRKT = 20;
  public static final int PLUS = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IXI_FILE",
  "XI_FILE",
  "IF",
  "ELSE",
  "RETURN",
  "USE",
  "WHILE",
  "LENGTH",
  "ID",
  "TYPE_INT",
  "TYPE_BOOL",
  "INT_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "BOOL_LITERAL",
  "L_PAREN",
  "R_PAREN",
  "L_SQ_BRKT",
  "R_SQ_BRKT",
  "L_BRACE",
  "R_BRACE",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "UNDERSCORE",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "MULT",
  "HIGH_MULT",
  "DIVIDE",
  "EQUALS",
  "NOT_EQUALS",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "NEG_BOOL",
  "REMAINDER",
  "LOGICAL_AND",
  "LOGICAL_OR"
  };
}

