
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package cyr7.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNDERSCORE = 24;
  public static final int R_BRACE = 20;
  public static final int LENGTH = 7;
  public static final int TYPE_BOOL = 10;
  public static final int LT = 34;
  public static final int L_PAREN = 15;
  public static final int error = 1;
  public static final int ASSIGN = 25;
  public static final int MINUS = 27;
  public static final int DIVIDE = 31;
  public static final int RETURN = 4;
  public static final int MULT = 28;
  public static final int SEMICOLON = 22;
  public static final int INT_LITERAL = 11;
  public static final int ELSE = 3;
  public static final int ID = 8;
  public static final int R_PAREN = 16;
  public static final int EOF = 0;
  public static final int IF = 2;
  public static final int L_BRACE = 19;
  public static final int L_SQ_BRKT = 17;
  public static final int COMMA = 23;
  public static final int TYPE_INT = 9;
  public static final int EQUALS = 32;
  public static final int USE = 5;
  public static final int HIGH_MULT = 30;
  public static final int LOGICAL_AND = 40;
  public static final int NOT_EQUALS = 33;
  public static final int COLON = 21;
  public static final int LOGICAL_OR = 41;
  public static final int EQ = 29;
  public static final int GT = 36;
  public static final int BOOL_LITERAL = 14;
  public static final int NEG_BOOL = 38;
  public static final int REMAINDER = 39;
  public static final int GTE = 37;
  public static final int WHILE = 6;
  public static final int STRING_LITERAL = 12;
  public static final int CHAR_LITERAL = 13;
  public static final int LTE = 35;
  public static final int R_SQ_BRKT = 18;
  public static final int PLUS = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "RETURN",
  "USE",
  "WHILE",
  "LENGTH",
  "ID",
  "TYPE_INT",
  "TYPE_BOOL",
  "INT_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "BOOL_LITERAL",
  "L_PAREN",
  "R_PAREN",
  "L_SQ_BRKT",
  "R_SQ_BRKT",
  "L_BRACE",
  "R_BRACE",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "UNDERSCORE",
  "ASSIGN",
  "PLUS",
  "MINUS",
  "MULT",
  "EQ",
  "HIGH_MULT",
  "DIVIDE",
  "EQUALS",
  "NOT_EQUALS",
  "LT",
  "LTE",
  "GT",
  "GTE",
  "NEG_BOOL",
  "REMAINDER",
  "LOGICAL_AND",
  "LOGICAL_OR"
  };
}

